package com.adaptivelearning.adaptivelearningbackend;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import jakarta.mail.internet.MimeMessage;

/**
 * Sends transactional emails for the registration OTP flow.
 *
 * Requires spring-boot-starter-mail on the classpath and the following
 * properties in application.properties (never commit real credentials):
 *
 *   spring.mail.host=smtp.gmail.com
 *   spring.mail.port=587
 *   spring.mail.username=your-address@gmail.com
 *   spring.mail.password=your-app-password
 *   spring.mail.properties.mail.smtp.auth=true
 *   spring.mail.properties.mail.smtp.starttls.enable=true
 *   app.mail.from=your-address@gmail.com
 *
 * For Gmail you must use an App Password (not your account password):
 *   Google Account → Security → 2-Step Verification → App passwords
 */
@Service
public class EmailService {

    @Autowired
    private JavaMailSender mailSender;

    @org.springframework.beans.factory.annotation.Value("${app.mail.from}")
    private String fromAddress;

    /**
     * Sends a 6-digit OTP to the given address so the user can confirm
     * ownership before their account is created.
     *
     * @param toEmail  the address to verify
     * @param otp      the 6-digit code generated by AuthController
     * @param fullName the user's display name (personalises the subject line)
     */
    public void sendVerificationOtp(String toEmail, String otp, String fullName) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom(fromAddress);
            helper.setTo(toEmail);
            helper.setSubject("Your verification code – Learning System");

            String html = buildOtpEmail(fullName, otp);
            helper.setText(html, true); // true = send as HTML

            mailSender.send(message);
            System.out.println("Verification OTP sent to: " + toEmail);
        } catch (Exception e) {
            // Log but don't swallow — AuthController needs to know the send
            // failed so it can return a meaningful error to the client.
            System.err.println("Failed to send verification email to " + toEmail + ": " + e.getMessage());
            throw new RuntimeException("Could not send verification email. Please check your email address and try again.", e);
        }
    }

    /**
     * Builds a clean, readable HTML email body for the OTP code.
     * Deliberately simple — no external resources, no images — so it
     * renders correctly across every major email client.
     */
    private String buildOtpEmail(String fullName, String otp) {
        String displayName = (fullName != null && !fullName.isBlank()) ? fullName : "there";
        return """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                  <title>Verify your email</title>
                </head>
                <body style="margin:0;padding:0;background:#f3f6f9;font-family:system-ui,-apple-system,'Segoe UI',Arial,sans-serif;">
                  <table width="100%%" cellpadding="0" cellspacing="0" style="background:#f3f6f9;padding:32px 16px;">
                    <tr>
                      <td align="center">
                        <table width="480" cellpadding="0" cellspacing="0"
                               style="background:#ffffff;border-radius:16px;border:1px solid #e2e8f0;
                                      box-shadow:0 4px 16px rgba(0,0,0,0.06);overflow:hidden;max-width:100%%;">

                          <!-- Header -->
                          <tr>
                            <td style="background:#192a3e;padding:28px 32px;">
                              <div style="display:inline-block;background:#FFD400;border-radius:10px;
                                          width:36px;height:36px;line-height:36px;text-align:center;
                                          font-weight:800;color:#002D72;font-size:18px;vertical-align:middle;">L</div>
                              <span style="color:#ffffff;font-weight:700;font-size:16px;
                                           vertical-align:middle;margin-left:10px;">Learning System</span>
                            </td>
                          </tr>

                          <!-- Body -->
                          <tr>
                            <td style="padding:36px 32px 28px;">
                              <p style="margin:0 0 6px;font-size:22px;font-weight:800;color:#111827;">
                                Verify your email 📬
                              </p>
                              <p style="margin:0 0 24px;font-size:15px;color:#6b7280;line-height:1.6;">
                                Hi %s, enter the code below to complete your registration.
                                It expires in <strong>5 minutes</strong>.
                              </p>

                              <!-- OTP box -->
                              <div style="background:#f0f9ff;border:2px solid #bae6fd;border-radius:14px;
                                          padding:28px;text-align:center;margin-bottom:24px;">
                                <div style="font-size:42px;font-weight:900;letter-spacing:14px;
                                            color:#0093ad;line-height:1;">%s</div>
                                <div style="font-size:13px;color:#6b7280;margin-top:10px;">
                                  Your one-time verification code
                                </div>
                              </div>

                              <p style="margin:0;font-size:13px;color:#9ca3af;line-height:1.6;">
                                If you didn't request this, you can safely ignore this email —
                                no account will be created without the code.
                              </p>
                            </td>
                          </tr>

                          <!-- Footer -->
                          <tr>
                            <td style="background:#f8fafc;border-top:1px solid #e2e8f0;
                                        padding:16px 32px;text-align:center;">
                              <p style="margin:0;font-size:12px;color:#9ca3af;">
                                © Learning System · This is an automated message, please do not reply.
                              </p>
                            </td>
                          </tr>

                        </table>
                      </td>
                    </tr>
                  </table>
                </body>
                </html>
                """.formatted(displayName, otp);
    }
}